site_name: TEFINANCE
site_description: App de finanzas personales para organizar ingresos, presupuestos, metas de ahorro y deudas.
site_author: MBL Development

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: indigo         # Color de la barra superior (puedes usar red, green, etc.)
    accent: indigo          # Color de enlaces y botones interactivos
  features:
    - navigation.tabs       # Menú en formato de pestañas superiores
    - navigation.sections   # Agrupar subsecciones de páginas
    - search.share          # Permitir compartir resultados de búsqueda

markdown_extensions:
  - attr_list
  - md_in_html 

extra_css:
  - assets/extra.css

site_url: https://amplexusagitta.com

nav:
  - Inicio: index.md
  - Política de Privacidad: privacidad.md
  - Términos y Condiciones: terminos.md
  - Eliminar Cuenta: eliminar-cuenta.md